name: Docker Build and Test

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Check out the repo content

    - name: Build Docker image
      run: |
        cd docker
        docker build . -t mr_planner-image

    - name: Check if ROS launch file works
      run: |
        timeout --signal=SIGINT 1m docker run --name mr_planner-container mr_planner-image -c "source /opt/ros/noetic/setup.bash && source /root/catkin_ws/devel/setup.bash && roslaunch mr_planner dual_gp4.launch demo:=true use_rviz:=false > output.txt 2>&1"
        docker cp mr_planner-container:/output.txt output.txt
        docker rm mr_planner-container
        if ! grep -q "Planning completed successfully" output.txt; then
          echo "Planning did not complete successfully"
          exit 1
        fi